# Lab Task 01

Write a function to return True if the first and last number of a given list is same. If numbers are different then return False.

In [23]:
def isSame(List):
    if(List[0] == List[-1]):
        return True
    else:
        return False

# Given:
numbers_x = [10, 20, 30, 40, 10]
numbers_y = [75, 65, 35, 75, 30]


print(isSame(numbers_x))
print(isSame(numbers_y))
# Expected Output:
# Given list: [10, 20, 30, 40, 10]
# result is True


# numbers_y = [75, 65, 35, 75, 30]
# result is False

True
False






# Lab Task 02

Create two NumPy arrays of the same shape and perform element-wise addition on them.

Calculate the element-wise product of two NumPy arrays.

In [24]:
#code here
import numpy as np

array_1 = np.array([1,2,3,4,5])
array_2 = np.array([6,7,8,9,10])

sum = array_1 + array_2
product = array_1 * array_2

print("Sum of Two Arrays : ")
print(sum)
print("Product of Two Arrays: ")
print(product)

Sum of Two Arrays : 
[ 7  9 11 13 15]
Product of Two Arrays: 
[ 6 14 24 36 50]


# Lab Task 03

Reshape a 1D NumPy array into a 2D array with dimensions (3, 4).

Concatenate two NumPy arrays horizontally and vertically.

In [25]:
#code here
array_1 = np.arange(0,12).reshape(3,4)
array_2 = np.arange(12,24).reshape(3,4)

print(np.concatenate((array_1,array_2),axis =0))
print(np.concatenate((array_1,array_2),axis = 1))

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]]
[[ 0  1  2  3 12 13 14 15]
 [ 4  5  6  7 16 17 18 19]
 [ 8  9 10 11 20 21 22 23]]


# Lab Task 04




## Online Store Shopping Cart
Write a Python program to simulate the online store's shopping cart system. The program should use a while loop to provide an interactive shopping experience.


### Tasks:
* Initialize an empty list called shopping_cart to store items.
* Display a welcome message and available products.
* Loop should be iterating over AI Response Simulator and Investment decision and keep asking for user input.
* Prompt the user to enter the number corresponding to the product they want to add to the cart.
* Check if the user entered 'q'. If so, break the loop.
* Convert the choice to an integer and validate it within the valid range (1 to 3).
* Based on the user's choice, add the selected product to the shopping_cart list.
* Display a confirmation message indicating the added product.
* Continue the loop to allow the user to add more products or proceed to checkout.
* After the loop ends, display the contents of the shopping cart.
* Display a goodbye message.
* End the program.


In [29]:
#Code here
shopping_cart = []
products =["Burger","Pizza","Fries"]
print("---------- WELCOME ----------------")
choice = 'y'
validate = [1,2,3]

while(choice !='q'):
    print("Add items in cart")
    print("Items : ",products)
    pick = int(input("Pick a Product : "))
    if(pick not in validate):
        print("invalid choice")
        continue
    shopping_cart.append(products[pick-1])
    print("Product has been added into the card.")

    Input = input("Do you want to continue ?(y/q)")
    choice = Input
    if(choice =="q"):
        print("Thank you for shopping.")

shopping_cart












---------- WELCOME ----------------
Add items in cart
Items :  ['Burger', 'Pizza', 'Fries']
invalid choice
Add items in cart
Items :  ['Burger', 'Pizza', 'Fries']
Product has been added into the card.
Thank you for shopping.


['Burger']

# Lab Task 05


## Email Classification
Develope a tool which will classify an email.

### Tasks:
* Create a function classify_emails that takes a list of emails as an argument.
* Inside the function, categorize emails into "Important," "Promotions," and "Spam" based on keywords and content analysis.
* Loop through the emails and identify keywords to determine their category.
* If an email contains keywords indicating importance, assign it as "Important."
* If an email contains keywords related to promotions or deals, assign it as "Promotions."
* If an email is suspected to be spam based on certain keywords or patterns, assign it as "Spam."
* Return three lists of emails for each category.
* Print the lists.

In [30]:
#code here

def classify_emails(emails):
    important = []
    promotion = []
    spam = []
    for i in range(len(emails)):
        email = emails[i]
        email = str(email)
        sp = True
        if("important" in email.lower() or "importants" in email.lower()):
            important.append(email)
            sp = False
        if("promotion" in email.lower() or "promotions" in email.lower() ):
            promotion.append(email)
            sp = False

        if(sp):
            spam.append(email)

        # if("important" not in email.lower() or "importants" not in email.lower() or "promotion" not in email.lower() or "promotions" not in email.lower()):
        #     spam.append(email)
    print("Important : ")
    print(important)
    print("Promotion : ")
    print(promotion)
    print("Spam  : ")
    print(spam)
    return important,promotion,spam

Emails = [["This email is very important"],["This email is for promotion"],["this email will go in spam folder"]]

classified_emails = classify_emails(Emails)
# classified_emails



Important : 
["['This email is very important']"]
Promotion : 
["['This email is for promotion']"]
Spam  : 
["['this email will go in spam folder']"]


# Lab Task 06

## English-Spanish Dictionary
You are creating a basic English-Spanish dictionary that allows users to look up English words and find their Spanish translations.


### Tasks
* Create a dictionary where English words are keys and their Spanish translations are values.
* Ask the user to input an English word.
* Check if the word exists in the dictionary.
* If the word exists, print its Spanish translation.
* If the word does not exist, inform the user that the translation is not available.
* Implement a loop that allows the user to keep looking up words until they choose to exit.


In [32]:
#code here

def Is_in_Dic(word,dict):
    for i in range(len(dict)):
        if(word == list(dict.keys())[i]):
            return True
dictionery = {"this":"este",
         "father":"padre",
         "friend":"amigo"}



while(True):
    word = input("Enter English word  : ")
    isExist =Is_in_Dic(word,dictionery)
    if(isExist):
        print("Spanish Translation : ",dictionery[word])
    else:
        print("Translation is not available")

    print("1. continue ")
    print("2. exit")

    choice = int(input("Enter choice : "))
    if(choice == 2):
        break
    else:
        continue


    


Spanish Translation :  este
1. continue 
2. exit
Spanish Translation :  padre
1. continue 
2. exit


# Lab Task 07

dataset link : https://raw.githubusercontent.com/TirendazAcademy/PANDAS-TUTORIAL/main/DataSets/vgsalesGlobale.csv
#Exercise
Use the dataset of Game, we have explored earlier and perform following operations.

* Calculate the total global sales for all games in the dataset.
* Find the game with the highest global sales.
* Determine the average sales for each region (NA_Sales, EU_Sales, JP_Sales, Other_Sales).
* Find the top 5 most popular game genres based on global sales.
* Calculate the total sales for each genre in each region and find the most popular genre in North America (NA_Sales).
* Display last 10 rows.
* Determine the top 3 gaming platforms with the highest global sales.
* Calculate the market share (percentage of global sales) for each genre.
* Calculate the correlation coefficient between NA_Sales and EU_Sales. (.corr function)

In [33]:
import pandas as pd

df = pd.read_csv("https://raw.githubusercontent.com/TirendazAcademy/PANDAS-TUTORIAL/main/DataSets/vgsalesGlobale.csv",index_col="Rank")
df

Name Platform    Year  \
Rank                                                                       
1                                            Wii Sports      Wii  2006.0   
2                                     Super Mario Bros.      NES  1985.0   
3                                        Mario Kart Wii      Wii  2008.0   
4                                     Wii Sports Resort      Wii  2009.0   
5                              Pokemon Red/Pokemon Blue       GB  1996.0   
...                                                 ...      ...     ...   
16596                Woody Woodpecker in Crazy Castle 5      GBA  2002.0   
16597                     Men in Black II: Alien Escape       GC  2003.0   
16598  SCORE International Baja 1000: The Official Game      PS2  2008.0   
16599                                        Know How 2       DS  2010.0   
16600                                  Spirits & Spells      GBA  2003.0   

              Genre   Publisher  NA_Sales  EU_Sales  JP_Sales  Other_Sales  \
Rank                                                                         
1            Sports    Nintendo     41.49     29.02      3.77         8.46   
2          Platform    Nintendo     29.08      3.58      6.81         0.77   
3            Racing    Nintendo     15.85     12.88      3.79         3.31   
4            Sports    Nintendo     15.75     11.01      3.28         2.96   
5      Role-Playing    Nintendo     11.27      8.89     10.22         1.00   
...             ...         ...       ...       ...       ...          ...   
16596      Platform       Kemco      0.01      0.00      0.00         0.00   
16597       Shooter  Infogrames      0.01      0.00      0.00         0.00   
16598        Racing  Activision      0.00      0.00      0.00         0.00   
16599        Puzzle    7G//AMES      0.00      0.01      0.00         0.00   
16600      Platform     Wanadoo      0.01      0.00      0.00         0.00   

       Global_Sales  
Rank                 
1             82.74  
2             40.24  
3             35.82  
4             33.00  
5             31.37  
...             ...  
16596          0.01  
16597          0.01  
16598          0.01  
16599          0.01  
16600          0.01  

[16598 rows x 10 columns]

In [34]:
# Total Global Sales for each Genre
global_sales=df.groupby("Genre")
sum = global_sales["Global_Sales"].sum()
sum

Genre
Action          1751.18
Adventure        239.04
Fighting         448.91
Misc             809.96
Platform         831.37
Puzzle           244.95
Racing           732.04
Role-Playing     927.37
Shooter         1037.37
Simulation       392.20
Sports          1330.93
Strategy         175.12
Name: Global_Sales, dtype: float64

In [35]:
"Highest Global Sales"
df["Genre"][df["Global_Sales"].idxmax()]

'Sports'

In [36]:
# Most Popular Genres

df.sort_values("Global_Sales",ascending=False).head(5)

Name Platform    Year         Genre Publisher  \
Rank                                                                      
1                   Wii Sports      Wii  2006.0        Sports  Nintendo   
2            Super Mario Bros.      NES  1985.0      Platform  Nintendo   
3               Mario Kart Wii      Wii  2008.0        Racing  Nintendo   
4            Wii Sports Resort      Wii  2009.0        Sports  Nintendo   
5     Pokemon Red/Pokemon Blue       GB  1996.0  Role-Playing  Nintendo   

      NA_Sales  EU_Sales  JP_Sales  Other_Sales  Global_Sales  
Rank                                                           
1        41.49     29.02      3.77         8.46         82.74  
2        29.08      3.58      6.81         0.77         40.24  
3        15.85     12.88      3.79         3.31         35.82  
4        15.75     11.01      3.28         2.96         33.00  
5        11.27      8.89     10.22         1.00         31.37

In [37]:
# Last 10 Rows

df.tail(10)

Name Platform    Year  \
Rank                                                                        
16591                                   Mega Brain Boost       DS  2008.0   
16592  Chou Ezaru wa Akai Hana: Koi wa Tsuki ni Shiru...      PSV  2016.0   
16593  Eiyuu Densetsu: Sora no Kiseki Material Collec...      PSP  2007.0   
16594                                Myst IV: Revelation       PC  2004.0   
16595                                           Plushees       DS  2008.0   
16596                 Woody Woodpecker in Crazy Castle 5      GBA  2002.0   
16597                      Men in Black II: Alien Escape       GC  2003.0   
16598   SCORE International Baja 1000: The Official Game      PS2  2008.0   
16599                                         Know How 2       DS  2010.0   
16600                                   Spirits & Spells      GBA  2003.0   

              Genre              Publisher  NA_Sales  EU_Sales  JP_Sales  \
Rank                                                                       
16591        Puzzle  Majesco Entertainment      0.01      0.00      0.00   
16592        Action        dramatic create      0.00      0.00      0.01   
16593  Role-Playing     Falcom Corporation      0.00      0.00      0.01   
16594     Adventure                Ubisoft      0.01      0.00      0.00   
16595    Simulation              Destineer      0.01      0.00      0.00   
16596      Platform                  Kemco      0.01      0.00      0.00   
16597       Shooter             Infogrames      0.01      0.00      0.00   
16598        Racing             Activision      0.00      0.00      0.00   
16599        Puzzle               7G//AMES      0.00      0.01      0.00   
16600      Platform                Wanadoo      0.01      0.00      0.00   

       Other_Sales  Global_Sales  
Rank                              
16591          0.0          0.01  
16592          0.0          0.01  
16593          0.0          0.01  
16594          0.0          0.01  
16595          0.0          0.01  
16596          0.0          0.01  
16597          0.0          0.01  
16598          0.0          0.01  
16599          0.0          0.01  
16600          0.0          0.01

In [38]:
rows = df.shape[0]
print("Average of NA Sales : ",df["NA_Sales"].sum()/rows)
print("Average of EU Sales : ",df["EU_Sales"].sum()/rows)
print("Average of EU Sales : ",df["JP_Sales"].sum()/rows)
print("Average of EU Sales : ",df["Other_Sales"].sum()/rows)

Average of NA Sales :  0.26466742981082064
Average of EU Sales :  0.14665200626581515
Average of EU Sales :  0.077781660441017
Average of EU Sales :  0.0480630196409206


In [18]:
Genres = df["Genre"].unique()
Genre = df.groupby("Genre")

for i in range(len(Genres)):
    print("Total Sales of  ",Genres[i]," : ",Genre.get_group(Genres[i])["NA_Sales"].sum())

for i in range(len(Genres)):
    print("Total Sales of  ",Genres[i]," : ",Genre.get_group(Genres[i])["EU_Sales"].sum())

for i in range(len(Genres)):
    print("Total Sales of  ",Genres[i]," : ",Genre.get_group(Genres[i])["JP_Sales"].sum())


Total Sales of   Sports  :  683.35
Total Sales of   Platform  :  447.05
Total Sales of   Racing  :  359.41999999999996
Total Sales of   Role-Playing  :  327.28
Total Sales of   Puzzle  :  123.78
Total Sales of   Misc  :  410.24
Total Sales of   Shooter  :  582.6
Total Sales of   Simulation  :  183.30999999999997
Total Sales of   Action  :  877.83
Total Sales of   Fighting  :  223.58999999999997
Total Sales of   Adventure  :  105.80000000000001
Total Sales of   Strategy  :  68.69999999999999
Total Sales of   Sports  :  376.85
Total Sales of   Platform  :  201.63000000000002
Total Sales of   Racing  :  238.39000000000001
Total Sales of   Role-Playing  :  188.05999999999997
Total Sales of   Puzzle  :  50.779999999999994
Total Sales of   Misc  :  215.98000000000002
Total Sales of   Shooter  :  313.27000000000004
Total Sales of   Simulation  :  113.38000000000001
Total Sales of   Action  :  525.0
Total Sales of   Fighting  :  101.32000000000001
Total Sales of   Adventure  :  64.13
Total Sal

In [39]:
Platform = df[df["Genre"] == "Platform"]
Platform.head(3)

Name Platform    Year     Genre Publisher  \
Rank                                                                   
2             Super Mario Bros.      NES  1985.0  Platform  Nintendo   
7         New Super Mario Bros.       DS  2006.0  Platform  Nintendo   
9     New Super Mario Bros. Wii      Wii  2009.0  Platform  Nintendo   

      NA_Sales  EU_Sales  JP_Sales  Other_Sales  Global_Sales  
Rank                                                           
2        29.08      3.58      6.81         0.77         40.24  
7        11.38      9.23      6.50         2.90         30.01  
9        14.59      7.06      4.70         2.26         28.62

In [40]:
df["NA_Sales"].corr(df["EU_Sales"])

0.767726748370264